apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: web
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "latest"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    replicaCount: 2
    service:
      type: ClusterIP
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
